In [7]:
# Pandas
import pandas as pd
print("Biblioteka załadowana!")

Biblioteka załadowana!

In [8]:
# Dane + BMI
pacjenci = [
    {"imie": "Jan", "waga": 85, "wzrost": 1.80},
    {"imie": "Anna", "waga": 60, "wzrost": 1.65},
    {"imie": "Marek", "waga": 110, "wzrost": 1.75}
]
df = pd.DataFrame(pacjenci)
df['BMI'] = df['waga'] / (df['wzrost'] ** 2)

In [9]:
# Kategoria
# Definiujemy progi (bins) i nazwy kategorii (labels)
progi = [0, 18.5, 25, 30, 100]
nazwy = ['Niedowaga', 'Norma', 'Nadwaga', 'Otyłość']

# Nowa kolumna 'Kategoria'
df['Kategoria'] = pd.cut(df['BMI'], bins=progi, labels=nazwy)

In [10]:
# Wynik
df

    imie  waga  wzrost        BMI Kategoria
0    Jan    85    1.80  26.234568   Nadwaga
1   Anna    60    1.65  22.038567     Norma
2  Marek   110    1.75  35.918367   Otyłość

In [13]:
# Sprawdzam podstawowe statystyki (średnia, odchylenie, min/max)
df.describe()

        waga    wzrost        BMI
count    3.0  3.000000   3.000000
mean    85.0  1.733333  28.063834
std     25.0  0.076376   7.118418
min     60.0  1.650000  22.038567
25%     72.5  1.700000  24.136568
50%     85.0  1.750000  26.234568
75%     97.5  1.775000  31.076468
max    110.0  1.800000  35.918367

In [ ]:
# Liczę, ilu pacjentów jest w kazdej kategorii
df['Kategoria'].value_counts()

Kategoria
Norma        1
Nadwaga      1
Otyłość      1
Niedowaga    0
Name: count, dtype: int64